version: "3.8"
services:
  webapp:
    build:
      context: ./app
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLUENTD_HOST=fluentd
      - PORT=5000
    depends_on:
      - fluentd
    networks:
      - backend

  fluentd:
    image: fluent/fluentd:v1.14-1
    ports:
      - "24224:24224"
    volumes:
      - "./fluentd/demo.conf:/fluentd/etc/demo.conf"
    environment:
      - FLUENTD_CONF=demo.conf
    networks:
      - backend

networks:
  backend: {}